### ISSUE TITLE
该方法有没有可能实现外置登录方案

### ISSUE THREAD

**Issue by DannerTomas** [sduoduo233/go-mcproxy#1]
如使用该ProxyServer连入时，ProxyServer执行某些特定操作用于第三方验证服务解决方案从而无需在mc客户端层面对YggdrasilMinecraftSessionService做任何修改。

**Comment by sduoduo233** [comment]
应该不行，外置正版验证应该要同时改客户端和服务端，go-mcproxy主要是用来做加速ip的，只实现了基于用户名的验证

**Comment by DannerTomas** [comment]
那能不能在login packet里获取到serverid呢

**Comment by sduoduo233** [comment]
可以获取到 serverid [https://wiki.vg/index.php?title=Protocol&oldid=7368#Login](https://wiki.vg/index.php?title=Protocol&oldid=7368#Login)
但是客户端到认证服务器的请求是获取不到的 [https://wiki.vg/Protocol_Encryption#Authentication](https://wiki.vg/Protocol_Encryption#Authentication)

**Comment by DannerTomas** [comment]
非常感谢，对于某些外置登录方案获取到serverid和修改username就已经完全够用了。

**Comment by sduoduo233** [comment]
网易开端是吧（）

**Comment by DannerTomas** [comment]
是的，就是网易（
代理服务端的一个思路

**Comment by CompassMatrix** [comment]
DannerTomas CAN HEIL THE NETEASE X19
